spring:
  datasource:
    type: org.apache.tomcat.jdbc.pool.DataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123
    url: jdbc:mysql://127.0.0.1:3306/jpa-test
  jpa:
    #使用正向工程在数据库生成表
    hibernate:
      ddl-auto: update
    #在控制台显示sql语句
    show-sql: true